AWSTemplateFormatVersion: '2010-09-09'

Resources:
  EventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S

  EventsTableNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !Ref EventsTable
